import image1 from "../images/card1.jpg";

const Data = [
  {
    id: 1,
    title: "Золотое кольцо Абхазии (из Адлера)",
    priceAdult: 1618,
    priceChild: 1412,
    duration: "2,5 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Абхазия",
    category: "Автобусный тур",
    people: 5,
  },
  {
    id: 2,
    title: "Роза Хутор и Красная Поляна",
    priceAdult: 1800,
    priceChild: 1500,
    duration: "5 часов",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Россия",
    category: "Джиппинг",
    people: 2,
  },
  {
    id: 3,
    title: "Обзорная экскурсия по Батуми",
    priceAdult: 1400,
    priceChild: 1100,
    duration: "3 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Грузия",
    category: "Яхтинг",
    people: 6,
  },
  {
    id: 4,
    title: "Стамбул: старый город и мечети",
    priceAdult: 2200,
    priceChild: 1800,
    duration: "6 часов",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Турция",
    category: "Автобусный тур",
    people: 5,
  },
  {
    id: 5,
    title: "Прогулка на катере по Босфору",
    priceAdult: 2500,
    priceChild: 2000,
    duration: "2 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Турция",
    category: "Яхтинг",
    people: 2,
  },
  {
    id: 6,
    title: "По следам древних цивилизаций (Тбилиси)",
    priceAdult: 1900,
    priceChild: 1600,
    duration: "4 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Грузия",
    category: "Каньонинг",
    people: 7,
  },
  {
    id: 7,
    title: "Секреты Баку: старая и новая столица",
    priceAdult: 2000,
    priceChild: 1700,
    duration: "5 часов",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Азербайджан",
    category: "Автобусный тур",
    people: 2,
  },
  {
    id: 8,
    title: "Шелковый путь: Самарканд и Бухара",
    priceAdult: 3000,
    priceChild: 2500,
    duration: "8 часов",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Узбекистан",
    category: "Автобусный тур",
    people: 7,
  },
  {
    id: 9,
    title: "Пляжный отдых в Батуми",
    priceAdult: 1300,
    priceChild: 1000,
    duration: "Целый день",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Грузия",
    category: "Джиппинг",
    people: 1,
  },
  {
    id: 10,
    title: "Тайны древнего Баку",
    priceAdult: 2200,
    priceChild: 1800,
    duration: "4,5 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Азербайджан",
    category: "Каньонинг",
    people: 4,
  },
  {
    id: 11,
    title: "Золотое кольцо Абхазии (из Адлера)",
    priceAdult: 1618,
    priceChild: 1412,
    duration: "2,5 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Абхазия",
    category: "Автобусный тур",
    people: 5,
  },
  {
    id: 12,
    title: "Роза Хутор и Красная Поляна",
    priceAdult: 1800,
    priceChild: 1500,
    duration: "5 часов",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Россия",
    category: "Джиппинг",
    people: 2,
  },
  {
    id: 13,
    title: "Обзорная экскурсия по Батуми",
    priceAdult: 1400,
    priceChild: 1100,
    duration: "3 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Грузия",
    category: "Яхтинг",
    people: 6,
  },
  {
    id: 14,
    title: "Стамбул: старый город и мечети",
    priceAdult: 2200,
    priceChild: 1800,
    duration: "6 часов",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Турция",
    category: "Автобусный тур",
    people: 5,
  },
  {
    id: 15,
    title: "Прогулка на катере по Босфору",
    priceAdult: 2500,
    priceChild: 2000,
    duration: "2 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Турция",
    category: "Яхтинг",
    people: 2,
  },
  {
    id: 16,
    title: "По следам древних цивилизаций (Тбилиси)",
    priceAdult: 1900,
    priceChild: 1600,
    duration: "4 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Грузия",
    category: "Каньонинг",
    people: 7,
  },
  {
    id: 17,
    title: "Секреты Баку: старая и новая столица",
    priceAdult: 2000,
    priceChild: 1700,
    duration: "5 часов",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Азербайджан",
    category: "Автобусный тур",
    people: 2,
  },
  {
    id: 18,
    title: "Шелковый путь: Самарканд и Бухара",
    priceAdult: 3000,
    priceChild: 2500,
    duration: "8 часов",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Узбекистан",
    category: "Автобусный тур",
    people: 7,
  },
  {
    id: 19,
    title: "Пляжный отдых в Батуми",
    priceAdult: 1300,
    priceChild: 1000,
    duration: "Целый день",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Грузия",
    category: "Джиппинг",
    people: 1,
  },
  {
    id: 20,
    title: "Тайны древнего Баку",
    priceAdult: 2200,
    priceChild: 1800,
    duration: "4,5 часа",
    description: "Вас ждет путешествие по Золотому Кольцу Абхазии...",
    image: image1,
    country: "Азербайджан",
    category: "Каньонинг",
    people: 4,
  },
];

export default Data;
